FORMAT: 1A
HOST: https://api.simplesat.io/api

# test-simplesat

# Group Examples

## Answer Collections [/answers]

### Retrieve all Answers [GET]

+ Request JSON Message

    + Headers

            Accept: application/json

+ Response 200 (application/json)

    + Headers

            X-My-Message-Header: 42

    + Body

            {
                "rating": "5",
                "sentiment": "positive"
            }

# Group Integrations

## Custom field mapping [/dashboard/integrations/custom_fields]

### Retrieve custom fields settings [GET]

+ Request (application/json)

+ Response 200

    + Attribute(object)
        - rating: Simplesat Rating (string) - ID to match with available field options
        - sentiment: Simplesat Sentiment (string) - ID to match with available field options
        - comment: Simplesat Comment (string) - ID to match with available field options

    + Body
    
            {
                "rating": "Simplesat Rating",
                "sentiment": "Simplesat Sentiment",
                "comment": "Simplesat Comment"
            }
            
### Save custom fields settings [POST]

+ Request (application/json)
    
    + Attribute(object)
        - rating: Simplesat Rating (string) - ID to match with available field options
        - sentiment: Simplesat Sentiment (string) - ID to match with available field options
        - comment: Simplesat Comment (string) - ID to match with available field options

    + Body
    
            {
                "rating": "Simplesat Rating",
                "sentiment": "Simplesat Sentiment",
                "comment": "Simplesat Comment"
            }
            
+ Response 200

    + Attribute(object)
        - rating: Simplesat Rating (string) - ID to match with available field options
        - sentiment: Simplesat Sentiment (string) - ID to match with available field options
        - comment: Simplesat Comment (string) - ID to match with available field options

    + Body
    
            {
                "rating": "Simplesat Rating",
                "sentiment": "Simplesat Sentiment",
                "comment": "Simplesat Comment"
            }

## Custom field mapping options [/dashboard/integrations/custom_fields/options]

### Retrieve available field options [GET]

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes(object)
    
        - id: 1 (number, required)
        - name: Simplesat Rating (string, required)
        - type: Number (enum[string], required) - Type of this customr field
            Member:
                - Text
                - Number
                - Enum
    + Body

            [
                {
                    "id": 1,
                    "name": "Simplesat Rating",
                    "type": "Number"
                },
                {
                    "id": 2,
                    "name": "Simplesat Comment",
                    "type": "Text"
                }
            ]